In [7]:
# -*- coding: utf-8 -*-
"""
Created by MinhKhang Nguyen
July 27 2021 7:37 PM
"""

'\nCreated by MinhKhang Nguyen\nJanuary 3 2021 11:54 AM\n'

In [438]:
import pandas as pd 
import random as rnd
import numpy as np 
import matplotlib.pyplot as plt

Importing Data

In [439]:
html_url = "https://www.basketball-reference.com/leagues/NBA_2021_per_game.html"

In [440]:
nba_tables = pd.read_html(html_url)

In [441]:
len(nba_tables)

1

In [442]:
nba = nba_tables[0]

In [443]:
nba.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,PF,21,MIA,61,4,12.1,2.0,3.7,...,.509,1.2,2.2,3.4,0.5,0.3,0.5,0.7,1.5,5.0
1,2,Jaylen Adams,PG,24,MIL,7,0,2.6,0.1,1.1,...,NaN,0.0,0.4,0.4,0.3,0.0,0.0,0.0,0.1,0.3
2,3,Steven Adams,C,27,NOP,58,58,27.7,3.3,5.3,...,.444,3.7,5.2,8.9,1.9,0.9,0.7,1.3,1.9,7.6
3,4,Bam Adebayo,C,23,MIA,64,64,33.5,7.1,12.5,...,.799,2.2,6.7,9.0,5.4,1.2,1.0,2.6,2.3,18.7
4,5,LaMarcus Aldridge,C,35,TOT,26,23,25.9,5.4,11.4,...,.872,0.7,3.8,4.5,1.9,0.4,1.1,1.0,1.8,13.5

In [444]:
nba.columns

Index(['Rk', 'Player', 'Pos', 'Age', 'Tm', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS'],
      dtype='object')

Cleaning DataFrame

In [445]:
#renames columns to strings only#
nba.rename(
    columns={
        'FG%': 'FGP',
        '3P': 'TP',
        '3PA': 'TPA',
        '3P%': 'TPP',
        '2P': 'TWOP',
        '2PA': 'TWOPA',
        '2P%': 'TWOPP',
        'eFG%': 'eFGP',
        'FT%': 'FTP'
    }, inplace=True)

#replacing NaN with 0#
nba.fillna(0)

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FTP,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,PF,21,MIA,61,4,12.1,2.0,3.7,...,.509,1.2,2.2,3.4,0.5,0.3,0.5,0.7,1.5,5.0
1,2,Jaylen Adams,PG,24,MIL,7,0,2.6,0.1,1.1,...,0,0.0,0.4,0.4,0.3,0.0,0.0,0.0,0.1,0.3
2,3,Steven Adams,C,27,NOP,58,58,27.7,3.3,5.3,...,.444,3.7,5.2,8.9,1.9,0.9,0.7,1.3,1.9,7.6
3,4,Bam Adebayo,C,23,MIA,64,64,33.5,7.1,12.5,...,.799,2.2,6.7,9.0,5.4,1.2,1.0,2.6,2.3,18.7
4,5,LaMarcus Aldridge,C,35,TOT,26,23,25.9,5.4,11.4,...,.872,0.7,3.8,4.5,1.9,0.4,1.1,1.0,1.8,13.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
726,536,Delon Wright,PG,28,SAC,27,8,25.8,3.9,8.3,...,.833,1.0,2.9,3.9,3.6,1.6,0.4,1.3,1.1,10.0
727,537,Thaddeus Young,PF,32,CHI,68,23,24.3,5.4,9.7,...,.628,2.5,3.8,6.2,4.3,1.1,0.6,2.0,2.2,12.1
728,538,Trae Young,PG,22,ATL,63,63,33.7,7.7,17.7,...,.886,0.6,3.3,3.9,9.4,0.8,0.2,4.1,1.8,25.3
729,539,Cody Zeller,C,28,CHO,48,21,20.9,3.8,6.8,...,.714,2.5,4.4,6.8,1.8,0.6,0.4,1.1,2.5,9.4
730,540,Ivica Zubac,C,23,LAC,72,33,22.3,3.6,5.5,...,.789,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0

In [446]:
nba.drop_duplicates(subset=['Player'], keep='first', inplace=True)
nba.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FTP,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Precious Achiuwa,PF,21,MIA,61,4,12.1,2.0,3.7,...,.509,1.2,2.2,3.4,0.5,0.3,0.5,0.7,1.5,5.0
1,2,Jaylen Adams,PG,24,MIL,7,0,2.6,0.1,1.1,...,NaN,0.0,0.4,0.4,0.3,0.0,0.0,0.0,0.1,0.3
2,3,Steven Adams,C,27,NOP,58,58,27.7,3.3,5.3,...,.444,3.7,5.2,8.9,1.9,0.9,0.7,1.3,1.9,7.6
3,4,Bam Adebayo,C,23,MIA,64,64,33.5,7.1,12.5,...,.799,2.2,6.7,9.0,5.4,1.2,1.0,2.6,2.3,18.7
4,5,LaMarcus Aldridge,C,35,TOT,26,23,25.9,5.4,11.4,...,.872,0.7,3.8,4.5,1.9,0.4,1.1,1.0,1.8,13.5

In [461]:
nba[["G", "GS","MP","FG","FGA","FGP","TP","TPA","TPP","TWOP","TWOPA","TWOPP","eFGP","FT","FTA","FTP","ORB","DRB","TRB","AST","STL","BLK","TOV","PF","PTS"]] = nba[["G", "GS","MP","FG","FGA","FGP","TP","TPA","TPP","TWOP","TWOPA","TWOPP","eFGP","FT","FTA","FTP","ORB","DRB","TRB","AST","STL","BLK","TOV","PF","PTS"]].apply(pd.to_numeric)
nba.loc[nba['G'] > 20]
nba.loc[nba['GS'] > 20]
nba.loc[nba['MP'] > 15]
nba.loc[nba['FG'] > 0.01]
nba.loc[nba['FGA'] > 0.01]
nba.loc[nba['FGP'] > 0.01]
nba.loc[nba['TP'] > 0.01]
nba.loc[nba['TPA'] > 0.01]
nba.loc[nba['TPP'] > 0.01]
nba.loc[nba['TWOP'] > 0.01]
nba.loc[nba['TWOPA'] > 0.01]
nba.loc[nba['TWOPP'] > 0.3]
nba.loc[nba['eFGP'] > 0.4]
nba.loc[nba['FT'] > 0.01]
nba.loc[nba['FTA'] > 0.01]
nba.loc[nba['FTP'] > 0.4]
nba.loc[nba['ORB'] > 0.01]
nba.loc[nba['DRB'] > 0.01]
nba.loc[nba['TRB'] > 0.01]
nba.loc[nba['AST'] > 0.01]
nba.loc[nba['STL'] > 0.01]
nba.loc[nba['BLK'] > 0.01]
nba.loc[nba['TOV'] > 0.01]
nba.loc[nba['PF'] > 0.01]
nba.loc[nba['PTS'] > 13]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,MVP Score
3,4,Bam Adebayo,C,23,MIA,64.0,64.0,33.5,7.1,12.5,...,2.2,6.7,9.0,5.4,1.2,1.0,2.6,2.3,18.7,2.129135
4,5,LaMarcus Aldridge,C,35,TOT,26.0,23.0,25.9,5.4,11.4,...,0.7,3.8,4.5,1.9,0.4,1.1,1.0,1.8,13.5,2.160445
17,12,Giannis Antetokounmpo,PF,26,MIL,61.0,61.0,33.0,10.3,18.0,...,1.6,9.4,11.0,5.9,1.2,1.2,3.4,2.8,28.1,NaN
20,15,Carmelo Anthony,PF,36,POR,69.0,3.0,24.5,4.7,11.3,...,0.5,2.6,3.1,1.5,0.7,0.6,0.9,2.1,13.4,NaN
22,17,OG Anunoby,SF,23,TOR,43.0,43.0,33.3,5.8,12.1,...,1.3,4.3,5.5,2.2,1.5,0.7,1.7,2.7,15.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
702,519,Derrick White,SG,26,SAS,36.0,32.0,29.6,5.2,12.6,...,0.4,2.6,3.0,3.5,0.7,1.0,1.3,2.5,15.4,NaN
706,522,Andrew Wiggins,PF,25,GSW,71.0,71.0,33.3,7.1,14.9,...,1.2,3.7,4.9,2.4,0.9,1.0,1.8,2.2,18.6,NaN
714,528,Zion Williamson,PF,20,NOP,61.0,61.0,33.2,10.4,17.0,...,2.7,4.5,7.2,3.7,0.9,0.6,2.7,2.2,27.0,NaN
722,534,Christian Wood,C,25,HOU,41.0,41.0,32.3,8.0,15.6,...,1.9,7.8,9.6,1.7,0.8,1.2,2.0,2.1,21.0,NaN
728,538,Trae Young,PG,22,ATL,63.0,63.0,33.7,7.7,17.7,...,0.6,3.3,3.9,9.4,0.8,0.2,4.1,1.8,25.3,NaN

Processing the Data

In [455]:
'''
scoring = (FGP/TPP/FTP)*(PTS)/(1-eFGP)
key = scoring/(TRB*AST*STL*BLK)
score = ((key*(TOV/PF))
score
'''

'\nscoring = (FGP/TPP/FTP)*(PTS)/(1-eFGP)\nkey = scoring/(TRB*AST*STL*BLK)\nscore = ((key*(TOV/PF))\nscore\n'

In [460]:
for index, row in nba.head().iterrows():
    nba.loc[index, "MVP Score"] = ((float(row['FGP']))*(float(row['TPP']))*(float(row['FTP'])))*(float(row['PTS']))
nba.head()

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,MVP Score
0,1,Precious Achiuwa,PF,21,MIA,61.0,4.0,12.1,2.0,3.7,...,1.2,2.2,3.4,0.5,0.3,0.5,0.7,1.5,5.0,0.000000
1,2,Jaylen Adams,PG,24,MIL,7.0,0.0,2.6,0.1,1.1,...,0.0,0.4,0.4,0.3,0.0,0.0,0.0,0.1,0.3,NaN
2,3,Steven Adams,C,27,NOP,58.0,58.0,27.7,3.3,5.3,...,3.7,5.2,8.9,1.9,0.9,0.7,1.3,1.9,7.6,0.000000
3,4,Bam Adebayo,C,23,MIA,64.0,64.0,33.5,7.1,12.5,...,2.2,6.7,9.0,5.4,1.2,1.0,2.6,2.3,18.7,2.129135
4,5,LaMarcus Aldridge,C,35,TOT,26.0,23.0,25.9,5.4,11.4,...,0.7,3.8,4.5,1.9,0.4,1.1,1.0,1.8,13.5,2.160445

Exporting to Excel File